//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фактическое: .
        /// </summary>
        public static string ActualRunTime {
            get {
                return ResourceManager.GetString("ActualRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить подзадачу.
        /// </summary>
        public static string AddChildTask {
            get {
                return ResourceManager.GetString("AddChildTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить задачу.
        /// </summary>
        public static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суммарное время выполнения подзадач.
        /// </summary>
        public static string ChildTaskRunTime {
            get {
                return ResourceManager.GetString("ChildTaskRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата завершения: .
        /// </summary>
        public static string CompleteDate {
            get {
                return ResourceManager.GetString("CompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание: .
        /// </summary>
        public static string DescriptionOfTask {
            get {
                return ResourceManager.GetString("DescriptionOfTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить изменения.
        /// </summary>
        public static string Error_CantSaveChanges {
            get {
                return ResourceManager.GetString("Error_CantSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string MSG_UnhandledError {
            get {
                return ResourceManager.GetString("MSG_UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла непредвиденная ошибка.
        /// </summary>
        public static string MSG_UnhandledError_Text {
            get {
                return ResourceManager.GetString("MSG_UnhandledError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        public static string NewPerformer {
            get {
                return ResourceManager.GetString("NewPerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Новая подзадача&gt;.
        /// </summary>
        public static string NewSubTaskName {
            get {
                return ResourceManager.GetString("NewSubTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Новая задача&gt;.
        /// </summary>
        public static string NewTaskName {
            get {
                return ResourceManager.GetString("NewTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель: .
        /// </summary>
        public static string PerformerName {
            get {
                return ResourceManager.GetString("PerformerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плановое: .
        /// </summary>
        public static string PlannedRunTime {
            get {
                return ResourceManager.GetString("PlannedRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата регистрации: .
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string RemoveTask {
            get {
                return ResourceManager.GetString("RemoveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначена.
        /// </summary>
        public static string Status_Assigned {
            get {
                return ResourceManager.GetString("Status_Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершена.
        /// </summary>
        public static string Status_Complete {
            get {
                return ResourceManager.GetString("Status_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется.
        /// </summary>
        public static string Status_InProgress {
            get {
                return ResourceManager.GetString("Status_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приостановлена.
        /// </summary>
        public static string Status_Stopped {
            get {
                return ResourceManager.GetString("Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус не найден.
        /// </summary>
        public static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование задачи: .
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время выполнения задачи.
        /// </summary>
        public static string TaskRunTime {
            get {
                return ResourceManager.GetString("TaskRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: .
        /// </summary>
        public static string TaskStatus {
            get {
                return ResourceManager.GetString("TaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление задачами.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить задачу:.
        /// </summary>
        public static string UI_AreYouSure_Remove {
            get {
                return ResourceManager.GetString("UI_AreYouSure_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string UI_Confirmation {
            get {
                return ResourceManager.GetString("UI_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string UI_DataGrid_Status {
            get {
                return ResourceManager.GetString("UI_DataGrid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача.
        /// </summary>
        public static string UI_DataGrid_Task {
            get {
                return ResourceManager.GetString("UI_DataGrid_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список подзадач:.
        /// </summary>
        public static string UI_ListOfSubTasks {
            get {
                return ResourceManager.GetString("UI_ListOfSubTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя задачи.
        /// </summary>
        public static string Valid_EnterTaskName {
            get {
                return ResourceManager.GetString("Valid_EnterTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестное свойство не прошло валидацию.
        /// </summary>
        public static string Valid_Error_UnknowProperty {
            get {
                return ResourceManager.GetString("Valid_Error_UnknowProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым.
        /// </summary>
        public static string Valid_NullField {
            get {
                return ResourceManager.GetString("Valid_NullField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача не может быть переведена в статус &apos;Завершена&apos;, т.к. одна из подзадач не завершена..
        /// </summary>
        public static string Valid_TaskCantBeSetToCompleted {
            get {
                return ResourceManager.GetString("Valid_TaskCantBeSetToCompleted", resourceCulture);
            }
        }
    }
}
